server:
  port: 7101
spring:
  jpa:
    show-sql: true
  datasource:
    database1:
      url: jdbc:mysql://localhost:3306/database1?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
    database2:
      url: jdbc:mysql://localhost:3306/database2?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver